### ISSUE TITLE
poppler-0.89.0-h72fac5a_2 no longer include C++ unstable API headers

### ISSUE THREAD

**Issue by rouault** [conda-forge/poppler-feedstock#101]
The new package
https://anaconda.org/conda-forge/poppler/0.89.0/download/linux-64/poppler-0.89.0-h72fac5a_2.tar.bz2
published recently no longer includes the include/poppler/Object.h file from the unstable C++ API. This breaks GDAL compilation: see https://github.com/OSGeo/gdal/issues/3396

Previous package
https://anaconda.org/conda-forge/poppler/0.89.0/download/linux-64/poppler-0.89.0-h4190859_1.tar.bz2 did include it

I believe the cause is this commit
https://github.com/conda-forge/poppler-feedstock/commit/6eb48acb569f2b77344a5411035398bfd5e2a3c9
which restores the use of -DENABLE_XPDF_HEADERS=ON instead of  -D ENABLE_UNSTABLE_API_ABI_HEADERS=True that is needed by poppler 0.89.0

CC @xhochy

**Comment by rouault** [comment]
Hum, I see this has been fixed in a later commit in https://github.com/conda-forge/poppler-feedstock/commit/fa8ebf5efa56a45fd9573cb83ec2092d29184a21 a few hours ago. I guess we must wait for updated packages now

**Comment by ocefpaf** [comment]
We may need to set this build as broken. I'll check this first thing tomorrow morning. Thanks for the report!

**Comment by rouault** [comment]
GDAL now builds again with the updated Poppler conda package

**Comment by pkgw** [comment]
Sounds like this can be closed? Apologies if I'm being too hasty here.

**Comment by xhochy** [comment]
We should mark those builds as broken, I'll put up a PR now.
