### ISSUE TITLE
Is it possible to create Windows win-32 pipeline for Poppler?

### ISSUE THREAD

**Issue by petko** [conda-forge/poppler-feedstock#109]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Currently, only win64 config is available for the Poppler package for Windows. Is it possible win32 Windows package to be added?

**Comment by ocefpaf** [comment]
Conda-forge dropped support for windows 32 a few years ago. We don't have enough workforce to do it and the use cases are quite rare. Also, setting up CIs for that is getting more and more difficult.

**Comment by petko** [comment]
I understand. Thank you!
