### ISSUE TITLE
pdftocairo converting only first page

### ISSUE THREAD

**Issue by frederick0291** [conda-forge/poppler-feedstock#111]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.
<br/>
Environment: <br/>
OS: Windows 10<br/>
Python: 3.9<br/>
Poppler: 21.08<br/>
<br/>
Issue:
<br/>
Converting pdf to TIFF only converts first page when using pdftocairo. I tried adding first and last pages, I also tried using even or odd pages but still only the first page of the array gets converted. Converting PDF to other formats like png or ppm successfully converts all pages. I have raised the issue in the main repo at gitlab but they said it was working properly for them.

`pdftocairo -tiff sample.pdf`
[sample.pdf](https://github.com/conda-forge/poppler-feedstock/files/7084957/sample.pdf)

**Comment by oschwartz10612** [comment]
Does this issue persist on 21.09?

**Comment by pkgw** [comment]
Are you able to check the exitcode of the program when this happens? Sometimes it's not obvious when Windows programs crash, and I'm wondering whether the program is crashing after it finishes exporting the first page.

**Comment by frederick0291** [comment]
I tested again and checked the exit code. 
`Exit Code is -1073740791`

**Comment by pkgw** [comment]
OK, if I'm doing this right, I think that's Windows error 0xC0000409 = `STATUS_STACK_BUFFER_OVERRUN`. So, yeah, some kind of crash in the program. If anyone's able to check this out in a debugger, that would be great — I'd like to try myself, but realistically I'm unlikely to be able to find the time.

**Comment by pkgw** [comment]
I tried running in a debugger in Windows but I can't figure out how to load in any symbol information, so all I can see is that it looks like the crash is due to an invalid argument to `fclose` ☹️

**Comment by pkgw** [comment]
After looking over the source ... this is a stab in the dark, but maybe file handle is getting `fclose()`d twice and that's causing an issue? Seems like the kind of thing that could potentially be OK on Unix systems but cause issues on Windows. There is an `fclose()` when poppler finishes a page image in `utils/pdftocairo.cc` (line 483), and I believe that the TIFF driver will close the associated file handle when the writer is closed (`libtiff/tif_win32.c` line 152, invoked by `TIFFClose`, invoked by `writer->close()` in pdftocairo).

**Comment by pkgw** [comment]
After doing a test build, it looks like my diagnosis above is correct. If I comment out the `fclose()` in `pdftocairo.cc`, the conversion succeeds.

**Comment by pkgw** [comment]
I have what I believe to be a proper solution in #117.

**Comment by oschwartz10612** [comment]
This is an impressive find. Thank you for the fix!

**Comment by frederick0291** [comment]
Thank you for the fix.
