### ISSUE TITLE
Build and ship poppler-qt

### ISSUE THREAD

**Issue by izahn** [conda-forge/poppler-feedstock#113]
I need poppler-qt but am not sure the best way to do that. All we would need to do here is add `qt` to the `host` requirements and cmake will do the rest. However, this will dramatically increase the size of `poppler` dependencies. Other options include making `poppler` a split package or just submitting a separate `poppler-qt` to staged recipes. How would you like me to proceed with this?

**Comment by pkgw** [comment]
@izahn Thanks for inquiring. If it's at all possible, I believe that a split package would be the right approach. I'm not an expert on setting up split packages by any means, but if you need some assistance figuring out how to try that approach, I'm more than happy to dig up examples and try to answer any questions you may have.

**Comment by izahn** [comment]
Split package does seem like the way to go. I will give it a try!

**Comment by izahn** [comment]
I've started this effort in https://github.com/conda-forge/poppler-feedstock/pull/114 but things are not going well. Appreciate any help!

**Comment by izahn** [comment]
We've made some progress in #14, getting close I hope.

**Comment by izahn** [comment]
Done in https://github.com/conda-forge/poppler-feedstock/pull/115
