### ISSUE TITLE
CI didn't run on main branch after merging poppler 23.10

### ISSUE THREAD

**Issue by akrherz** [conda-forge/poppler-feedstock#152]
### Comment:

I could be totally wrong, but I think a main branch CI build never ran after merging 23.10

https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=799 shows nothing

https://anaconda.org/conda-forge/poppler/files shows no builds

conda-forge/gdal-feedstock#828 found no artifacts available

**Comment by xylar** [comment]
Sometimes, this means the token needs to be reset at https://github.com/conda-forge/admin-requests.  I don't see any CI so it's hard to know.  Maybe we can push an empty commit and see if that does the trick this time.

**Comment by xylar** [comment]
Let's keep an eye on https://github.com/conda-forge/poppler-feedstock/runs/17653037229 and see if that does the trick.

**Comment by akrherz** [comment]
thanks @xylar, looks to be working as I see an artifact on anaconda.org now.

**Comment by xylar** [comment]
CI has been glitching far too often lately.
