### ISSUE TITLE
WinError126 during poppler installation with conda

### ISSUE THREAD

**Issue by Aeksioglu** [conda-forge/poppler-feedstock#50]
Hi , 
trying to install poppler package to conda with conda install -c conda-forge poppler.
Anaconda run the command and prompted to download below packages but none of them is successful due to the WinError126 error. I can able to download package with pip install but it is difficult to move the packages. please help about it.  

Proceed ([y]/n)? y
Downloading and Extracting Packages
lz4-c-1.8.3          | 255 KB    |                                                                                                    |   poppler-0.80.0       | 1.9 MB    |                                                                                                    |   pcre-8.41            | 453 KB    |                                                                                                    |   libcurl-7.65.3       | 270 KB    |                                                                                                    |   freetype-2.10.0      | 476 KB    |                                                                                                    |   ca-certificates-2019 | 181 KB    |                                                                                                    |   zlib-1.2.11          | 236 KB    |                                                                                                    |   zstd-1.4.0           | 1.5 MB    |                                                                                                    |   libiconv-1.15        | 673 KB    |                                                                                                    |   libffi-3.2.1         | 36 KB     |                                                                                                    |   0%
jpeg-9c              | 314 KB    |                                                                                                    |   tk-8.6.9             | 3.7 MB    |                                                                                                    |   libtiff-4.0.10       | 1020 KB   |                                                                                                    |   vs2015_runtime-14.16 | 2.4 MB    |                                                                                                    krb5-1.16.3          | 819 KB    |                                                                                                    |   libssh2-1.8.2        | 186 KB    |                                                                                                    |   gettext-0.19.8.1     | 5.0 MB    |                                                                                                    |   xz-5.2.4             | 805 KB    |                                                                                                    |   ibpng-1.6.37        | 1.3 MB    |                                                                                                    |   curl-7.65.3          | 113 KB    |                                                                                                    |   poppler-data-0.4.9   | 3.4 MB    |                                                                                                    glib-2.58.3          | 3.5 MB    |                                                                                                    |   openjpeg-2.3.1       | 226 KB    |                                                                                                    |   

[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found
[WinError 126] The specified module could not be found

**Comment by pkgw** [comment]
If the error happens *during the installation phase*, I do not think it is related to the `poppler` package in particular. I suggest that you ask about this error on the conda-forge Gitter channel: https://gitter.im/conda-forge/conda-forge.github.io — hopefully someone there will have a better idea of where this might be coming from.

**Comment by Aeksioglu** [comment]
Thanks a lot for your suggestion, Peter. I have asked about the it accordingly.
