### ISSUE TITLE
Building for windows locally

### ISSUE THREAD

**Issue by martijnburgers** [conda-forge/poppler-feedstock#60]
Searching for help building poppler for Windows locally. Would this be difficult using the conda-forge scripts?

**Comment by pkgw** [comment]
I'm not sure if I fully understand your question — is it that you want to build Poppler on your local Windows machine, and you are wondering whether it might make sense to use the conda-forge build scripts as a starting point?

If that's the question, it's hard to give a definitive answer. A lot depends on what toolchain you're using and how you need to integrate with any dependency libraries. The build script used in this package is fairly generic but a lot of the tricky work in building a library like this is involved in getting the dependencies set up the right way, and that work is automated by the conda build system.

Ultimately we're not positioned to provide advice about building packages outside of the conda-forge framework. [This StackExchange question](https://stackoverflow.com/questions/18381713/how-to-install-poppler-on-windows) has a range of solutions (note the dates — some of them are more than 5 years old at this point).

**Comment by martijnburgers** [comment]
That was the question. I will try some stuff out. Thanks for replying.
