### ISSUE TITLE
Cairo/pdftocairo support not included on Windows

### ISSUE THREAD

**Issue by oschwartz10612** [conda-forge/poppler-feedstock#66]
Hi,

I was wondering if it is possible to build `pdftocairo` for the Windows releases? 

Right now it is not built and prevents usages of tiffs in some cases. For example: [pdf2image](https://github.com/Belval/pdf2image/issues/145)

Thanks.

**Comment by pkgw** [comment]
See some of the discussion in #35. Poppler expects Cairo to be built with FreeType support, and conda-forge's cairo is not built with FreeType support right now. In order to fix this, we'd need to add FreeType to Cairo on Windows.

**Comment by oschwartz10612** [comment]
I see. Thanks for the reply. I will see if I can jump further down this rabbit hole.

**Comment by pkgw** [comment]
Fixed in #67.
