### ISSUE TITLE
Poppler update started failing fiona package

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/poppler-feedstock#7]
See https://github.com/conda-forge/fiona-feedstock/issues/62

**Comment by jorisvandenbossche** [comment]
OK, I assume this is the reason for the breakage: https://github.com/conda-forge/conda-forge.github.io/pull/490, and this update (and the pinning in other packages) is actually the attempt to solve it!

**Comment by ocefpaf** [comment]
Thanks @jorisvandenbossche. I had hopes that we could just move to `libgdal >=2.2`, but `fiona` is still needs `libgdal 2.1` so I submitted #8 to solve that.
