### ISSUE TITLE
Poppler data encodings not recognized on Windows

### ISSUE THREAD

**Issue by oschwartz10612** [conda-forge/poppler-feedstock#76]
Hi,

It's me again, sorry...

I am trying to get the additional encodings in poppler-data to work, but when running `pdfinfo -listenc`, the additional encodings do not show up.

I noticed in `cmakelists.win.patch` that the poppler-data files are supposed to be placed in `/share/poppler`, and other sources seem to concur. I placed the files in `/bin/share/poppler`, but no success. I messed around with putting the files in all sorts of places but I cant seem to get the encodings to show up.

I am assuming I am making a stupid mistake here...

Thanks you for your time.

**Comment by pkgw** [comment]
Hi — am I inferring correctly that you're running on Windows? I believe that I'm getting the correct behavior on Linux, but I can see how Windows might have problems.

For future reference: see [GlobalParams.cc](https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/poppler/GlobalParams.cc#L436). Encoding listing comes from `*UnicodeMaps` in that class, augmented in `addUnicodeMap` method.

**Comment by oschwartz10612** [comment]
Yes, this issue is on Windows. Apologies for not mentioning.

I still have been unable to get it to pick up the data files.

**Comment by pkgw** [comment]
OK, I think this will start working in the next build.

**Comment by oschwartz10612** [comment]
I am still not seeing the encodings show up using the new build. Are you seeing the same behavior, or am I doing something incredibly stupid?

**Comment by pkgw** [comment]
It is working on my test VM. Are you sure that you're getting the latest package? It should have a version of:

```
poppler-20.12.1-h7cbfaf2_1
```

It relies on some libraries that are being migrated right now (glib, icu) so you might not be getting the latest package if you're installing into an environment that needs slightly older versions of those.

**Comment by oschwartz10612** [comment]
I am using `poppler-20.12.1-h7cbfaf2_1`; I pulled it from `https://anaconda.org/` just to be sure. I must be doing something wrong. I am getting
```cmd
C:\Users\Owen Schwartz\Downloads\poppler\Library\bin>pdfinfo -listenc
Available encodings are:
ASCII7
Latin1
Symbol
UTF-16
UTF-8
ZapfDingbats
```
with the poppler-data files in `\Library\bin\share\poppler`. 

Trust me, if I didn't have to use windows I wouldn't be... Thanks for all of your assistance.

**Comment by pkgw** [comment]
Ah. The poppler-data files should be landing where the `poppler-data` package puts them, which should be in `share\poppler` *not* in the `Library`, or `Library\bin`, directory.

**Comment by oschwartz10612** [comment]
Yep, that was my problem. I knew I was doing something stupid!

Thanks again for all of your help!
